### PR TITLE
Add create_cells() impls to elasticsearch & loki

### PR DESCRIPTION
**Pull request by actualwitch**
# Description

This pr adds `create_cells()` to elasticsearch and loki providers. This resolves [FP-3078](https://linear.app/fiberplane/issue/FP-3078/elasticsearch-direct-access-doesnt-work).

# Checklist

Please make sure all of these are checked before merging. Please leave items
you think are non-applicable in the list, but use strike-through (`~~`) to
indicate they don't apply.

- [x] The feature is tested.
- [x] The CHANGELOG is updated.

### CODE REVIEW

**Review by arendjr — APPROVED** [review]
Great!

**Comment by arendjr** [comment]
Can you run `cargo update -p fiberplane-models`? I suspect the lock file that was merged into `main` might've broken the build.

**Comment by actualwitch** [comment]
when i run it it doesn't change anything in lockfile. OTOH in the log of github actions i can see `Permission denied (publickey).` which is kinda weird ngl

**Comment by arendjr** [comment]
This should do the trick. Thanks to @hatchan for helping me investigate :)

**Pull request merged**
